## Wrnagling - geo_json ready

In [1]:
import pandas as pd

In [118]:
data = pd.read_csv('Data/Cafe__restaurant__bistro_seats_2015_map.csv')

In [119]:
data['Industry (ANZSIC4) code'].unique()

array([4511, 4512, 4520, 9113, 9112, 4129, 4400, 9209, 9003, 9001, 1174,
       9111, 4530, 1182, 4244, 5910, 4279, 4274, 9559, 8921, 4513, 9520,
       4111, 7299, 4213, 9139, 4110, 9540, 9121, 9539, 8101, 4122, 4123,
       3911, 9412, 8790, 9201, 6712])

In [121]:
data[data['Industry (ANZSIC4) code']==9003].head(5)

,Census year,Block ID,Property ID,Base property ID,Street address,CLUE small area,Trading name,Industry (ANZSIC4) code,Industry (ANZSIC4) description,Seating type,Number of seats,Location
411,2015,67,103602,103602,199-219 Exhibition Street,Melbourne (CBD),Her Majesty's Theatre,9003,Performing Arts Venue Operation,Seats - Indoor,40,"(-37.81093839, 144.9695458)"
412,2015,67,103602,103602,199-219 Exhibition Street,Melbourne (CBD),Her Majesty's Theatre,9003,Performing Arts Venue Operation,Seats - Outdoor,16,"(-37.81093839, 144.9695458)"

In [132]:
# Remove brackets, dots, split one location column into Latitude and Longitude
def extract(data, code):
    df = data[data['Industry (ANZSIC4) code']==code]
    df.loc[:,'Location'] = df.loc[:,'Location'].str.replace('(','')
    df.loc[:,'Location'] = df.loc[:,'Location'].str.replace(')','')
    df[['Latitude', 'Longitude']] = df.loc[:,'Location'].str.split(',', n=1, expand=True)
    df = df.drop(['Location'], axis=1)
    df = df.reset_index(drop=True)
    return df

In [133]:
cafe_restaurant = extract(data, 4511)
pubs = extract(data, 4520)
takeaway = extract(data, 4512)
accomodation = extract(data, 4400)
performing_art = extract(data, 9003)

/Users/plus/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/Users/plus/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3140: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

In [134]:
pubs

,Census year,Block ID,Property ID,Base property ID,Street address,CLUE small area,Trading name,Industry (ANZSIC4) code,Industry (ANZSIC4) description,Seating type,Number of seats,Latitude,Longitude
0,2015,242,104461,104461,191-197 Grattan Street,Carlton,Prince Alfred Hotel,4520,"Pubs, Taverns and Bars",Seats - Indoor,40,-37.80045792,144.962209
1,2015,242,104461,104461,191-197 Grattan Street,Carlton,Prince Alfred Hotel,4520,"Pubs, Taverns and Bars",Seats - Outdoor,30,-37.80045792,144.962209
2,2015,257,105516,105516,154-160 Leicester Street,Carlton,The Corkman Irish Pub,4520,"Pubs, Taverns and Bars",Seats - Indoor,150,-37.80243195,144.960916
3,2015,257,105516,105516,154-160 Leicester Street,Carlton,The Corkman Irish Pub,4520,"Pubs, Taverns and Bars",Seats - Outdoor,10,-37.80243195,144.960916
4,2015,266,106081,106081,27-31 Lygon Street,Carlton,John Curtin Hotel,4520,"Pubs, Taverns and Bars",Seats - Indoor,71,-37.80619915,144.9656988
5,2015,266,106081,106081,27-31 Lygon Street,Carlton,John Curtin Hotel,4520,"Pubs, Taverns and Bars",Seats - Outdoor,16,-37.80619915,144.9656988
6,2015,215,108202,108202,415-421 Rathdowne Street,Carlton,The Beaufort,4520,"Pubs, Taverns and Bars",Seats - Indoor,80,-37.79652005,144.9704262
7,2015,218,106215,106215,298 Lygon Street,Carlton,Carlton Yacht Club Bar,4520,"Pubs, Taverns and Bars",Seats - Outdoor,40,-37.79998572,144.9673764
8,2015,267,106251,106251,66-88 Lygon Street,Carlton,Lagers On Lygon,4520,"Pubs, Taverns and Bars",Seats - Indoor,30,-37.80530329,144.9665747
9,2015,218,106222,106222,270-276 Lygon Street,Carlton,University Hotel,4520,"Pubs, Taverns and Bars",Seats - Indoor,60,-37.8005263,144.9672432
10,2015,218,106222,106222,270-276 Lygon Street,Carlton,University Hotel,4520,"Pubs, Taverns and Bars",Seats - Outdoor,58,-37.8005263,144.9672432
11,2015,264,109322,109322,593-597 Swanston Street,Carlton,Queensberry Hotel,4520,"Pubs, Taverns and Bars",Seats - Indoor,60,-37.80475348,144.9629068
12,2015,204,101613,101613,377-391 Cardigan Street,Carlton,Clyde Hotel,4520,"Pubs, Taverns and Bars",Seats - Indoor,70,-37.79725532,144.9657541
13,2015,204,101613,101613,377-391 Cardigan Street,Carlton,Clyde Hotel,4520,"Pubs, Taverns and Bars",Seats - Outdoor,50,-37.79725532,144.9657541
14,2015,255,101593,101593,91-95 Cardigan Street,Carlton,Hotel Lincoln,4520,"Pubs, Taverns and Bars",Seats - Indoor,62,-37.80448528,144.9645057
15,2015,255,101593,101593,91-95 Cardigan Street,Carlton,Hotel Lincoln,4520,"Pubs, Taverns and Bars",Seats - Outdoor,20,-37.80448528,144.9645057
16,2015,214,106186,106186,414-422 Lygon Street,Carlton,Astor Hotel,4520,"Pubs, Taverns and Bars",Seats - Indoor,40,-37.79694555,144.9678126
17,2015,247,106238,106238,192-202 Lygon Street,Carlton,Players On Lygon,4520,"Pubs, Taverns and Bars",Seats - Outdoor,20,-37.80245924,144.9670522
18,2015,252,106244,106244,160-162 Lygon Street,Carlton,Bar Centrale,4520,"Pubs, Taverns and Bars",Seats - Indoor,73,-37.80344164,144.9667699
19,2015,252,106244,106244,160-162 Lygon Street,Carlton,Bar Centrale,4520,"Pubs, Taverns and Bars",Seats - Outdoor,50,-37.80344164,144.9667699
20,2015,260,103276,103276,614-616 Elizabeth Street,Carlton,The Last Jar,4520,"Pubs, Taverns and Bars",Seats - Indoor,90,-37.80389369,144.9589387
21,2015,37,102158,102158,86-88 Collins Street,Melbourne (CBD),Collins Quarter,4520,"Pubs, Taverns and Bars",Seats - Indoor,171,-37.81393777,144.9705847
22,2015,37,102158,102158,86-88 Collins Street,Melbourne (CBD),Collins Quarter,4520,"Pubs, Taverns and Bars",Seats - Outdoor,90,-37.81393777,144.9705847
23,2015,57,106433,106433,18-24 Market Lane,Melbourne (CBD),Ding Dong Lounge,4520,"Pubs, Taverns and Bars",Seats - Indoor,80,-37.81175137,144.9694031
24,2015,57,101217,101217,124-128 Bourke Street,Melbourne (CBD),Welcome Stranger,4520,"Pubs, Taverns and Bars",Seats - Indoor,60,-37.81207094,144.9692645
25,2015,57,103599,103599,169-171 Exhibition Street,Melbourne (CBD),1806,4520,"Pubs, Taverns and Bars",Seats - Indoor,107,-37.81165123,144.9700684
26,2015,17,103925,103925,121-123 Flinders Lane,Melbourne (CBD),Fashion Lounge,4520,"Pubs, Taverns and Bars",Seats - Indoor,100,-37.81567009,144.9705132
27,2015,77,108573,108573,270 Russell Street,Melbourne (CBD),Whisky and Alement,4520,"Pubs, Taverns and Bars",Seats - Indoor,45,-37.81011116,144.9671591
28,2015,57,101221,101221,94-96 Bourke Street,Melbourne (CBD),The Elephant and Wheelbarrow,4520,"Pubs, Taverns and Bars",Seats - Indoor,240,-37.81191058,144.9702485
29,2015,57,101221,101221,94-96 Bourke Street,Melbourne (CBD),The Elephant and Wheelbarrow,4520,"Pubs, Taverns and Bars",Seats - Outdoor,36,-37.81191058,144.9702485
...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,2015,915,108456,108456,43-49 Royal Parade,Parkville,Naughtons Parkville Hotel,4520,"Pubs, Taverns and Bars",Seats - Outdoor,36,-37.79554181,144.9575345
172,2015,774,600431,600431,816 Lorimer Street,Port Melbourne,Underbridge Sports Bar & Cafe,4520,"Pubs, Taverns and Bars",Seats - Indoor,52,-37.82210926,144.9309535
173,2015,774,600431,600431,816 Lorimer Street,Port Melbourne,Underbridge Sports Bar & Cafe,4520,"Pubs, Taverns and Bars",Seats - Outdoor,24,-37.82210926,144.9309535
174,2015,804,110988,110988,29-65 South Wharf Promenade,Southbank,Munich Brau Haus,4520,"Pubs, Taverns and Bars",Seats - Indoor,250,-37.82409303,144.9503336
175,2015,804,110988,110988,29-65 South Wharf Promenade,Southbank,Munich Brau Haus,4520,"Pubs, Taverns and Bars",Seats - Outdoor,150,-37.82409303,144.9503336
176,2015,803,111175,110477,8 Whiteman Street,Southbank,Lumia Bar,4520,"Pubs, Taverns and Bars",Seats - Indoor,110,-37.82312164,144.9586604
177,2015,803,111175,110477,8 Whiteman Street,Southbank,Lumia Bar,4520,"Pubs, Taverns and Bars",Seats - Outdoor,30,-37.82312164,144.9586604
178,2015,801,559161,559161,3-7 Riverside Quay,Southbank,Belgian Beer Cafe Melbourne,4520,"Pubs, Taverns and Bars",Seats - Indoor,150,-37.82166549,144.9645668
179,2015,801,559161,559161,3-7 Riverside Quay,Southbank,Belgian Beer Cafe Melbourne,4520,"Pubs, Taverns and Bars",Seats - Outdoor,60,-37.82166549,144.9645668
180,2015,753,110606,110380,3 Southgate Avenue,Southbank,P J O'Briens Irish Pub & Side Bar,4520,"Pubs, Taverns and Bars",Seats - Indoor,150,-37.82066923,144.9662623
181,2015,753,110323,110380,1 Southgate Avenue,Southbank,Aria Bar & Lounge,4520,"Pubs, Taverns and Bars",Seats - Indoor,63,-37.82066923,144.9662623
182,2015,752,108653,110733,100 St Kilda Road,Southbank,Mezz Bar,4520,"Pubs, Taverns and Bars",Seats - Indoor,20,-37.82094188,144.9682264
183,2015,724,106798,106798,557 St Kilda Road,Melbourne (Remainder),"Village Melbourne - Garden, Arbor, Bistro & Te...",4520,"Pubs, Taverns and Bars",Seats - Indoor,140,-37.84752524,144.9814116
184,2015,724,106798,106798,557 St Kilda Road,Melbourne (Remainder),"Village Melbourne - Garden, Arbor, Bistro & Te...",4520,"Pubs, Taverns and Bars",Seats - Outdoor,800,-37.84752524,144.9814116
185,2015,427,108867,108867,515-523 Spencer Street,West Melbourne (Residential),Royal Mail Hotel On Spencer,4520,"Pubs, Taverns and Bars",Seats - Indoor,55,-37.80844822,144.9482732
186,2015,427,108867,108867,515-523 Spencer Street,West Melbourne (Residential),Royal Mail Hotel On Spencer,4520,"Pubs, Taverns and Bars",Seats - Outdoor,15,-37.80844822,144.9482732
187,2015,101,108949,108949,396-400 Spencer Street,West Melbourne (Residential),Carron Tavern (Spencer Street) Pty Ltd,4520,"Pubs, Taverns and Bars",Seats - Indoor,200,-37.81114228,144.9508616
188,2015,101,108949,108949,396-400 Spencer Street,West Melbourne (Residential),Carron Tavern (Spencer Street) Pty Ltd,4520,"Pubs, Taverns and Bars",Seats - Outdoor,45,-37.81114228,144.9508616
189,2015,439,102962,102962,78-86 Dudley Street,West Melbourne (Residential),Witches In Britches Pty Ltd,4520,"Pubs, Taverns and Bars",Seats - Indoor,350,-37.80890193,144.952636
190,2015,424,109710,109710,315 Victoria Street,West Melbourne (Residential),The Bodega,4520,"Pubs, Taverns and Bars",Seats - Indoor,20,-37.80556768,144.9510475
191,2015,424,109710,109710,315 Victoria Street,West Melbourne (Residential),The Bodega,4520,"Pubs, Taverns and Bars",Seats - Outdoor,8,-37.80556768,144.9510475
192,2015,435,107481,107481,65-67 Peel Street,West Melbourne (Residential),The Drunken Poet Pty Ltd,4520,"Pubs, Taverns and Bars",Seats - Indoor,35,-37.80666721,144.955498
193,2015,435,107481,107481,65-67 Peel Street,West Melbourne (Residential),The Drunken Poet Pty Ltd,4520,"Pubs, Taverns and Bars",Seats - Outdoor,12,-37.80666721,144.955498
194,2015,441,108856,108856,475-477 Spencer Street,West Melbourne (Residential),Hotel Spencer Bar & Dining Room,4520,"Pubs, Taverns and Bars",Seats - Indoor,90,-37.80956913,144.9492503
195,2015,441,108856,108856,475-477 Spencer Street,West Melbourne (Residential),Hotel Spencer Bar & Dining Room,4520,"Pubs, Taverns and Bars",Seats - Outdoor,12,-37.80956913,144.9492503
196,2015,423,109721,109721,361-365 Victoria Street,West Melbourne (Residential),Three Crowns Hotel,4520,"Pubs, Taverns and Bars",Seats - Indoor,91,-37.80539883,144.9494595
197,2015,423,109721,109721,361-365 Victoria Street,West Melbourne (Residential),Three Crowns Hotel,4520,"Pubs, Taverns and Bars",Seats - Outdoor,40,-37.80539883,144.9494595
198,2015,424,109709,109709,313 Victoria Street,West Melbourne (Residential),Clever Polly's,4520,"Pubs, Taverns and Bars",Seats - Indoor,30,-37.80556778,144.9510931
199,2015,424,109709,109709,313 Victoria Street,West Melbourne (Residential),Clever Polly's,4520,"Pubs, Taverns and Bars",Seats - Outdoor,8,-37.80556778,144.9510931
200,2015,437,110111,110111,333-337 William Street,West Melbourne (Residential),Royal Standard Hotel,4520,"Pubs, Taverns and Bars",Seats - Indoor,150,-37.80781408,144.9542537

In [135]:
cafe_restaurant.to_csv('./Data/cafe_restaurant.csv')
pubs.to_csv('./Data/pubs.csv')
takeaway.to_csv('./Data/takeaway.csv')
accomodation.to_csv('./Data/accomodation.csv')
performing_art.to_csv('./Data/performing_art.csv')

## Extract Public Art

In [2]:
data = pd.read_csv('Public_artworks__fountains_and_monuments.csv')

In [27]:
data.head(1)

,Asset Type,Name,Xorg,Xsource,Address Point,Artist,Alternate Name,Art Date,Mel way Ref,Respective Author,Structure,Co-ordinates,Easting,Northing
0,Fountain,Coles Fountain,City of Melbourne,MCC - Ortho Image March 2005 - Final,"517 Albert Street, EAST MELBOURNE",Robert Woodward,NaN,1981,2F_J1,City Of Melbourne,Stainless-steel fountain on bluestone paving,"(-37.8097706189194, 144.973483976518)",321609.36,5813356.512

In [7]:
def extract2(data, code):
    df = data[data['Asset Type']==code]
    df.loc[:,'Co-ordinates'] = df.loc[:,'Co-ordinates'].str.replace('(','')
    df.loc[:,'Co-ordinates'] = df.loc[:,'Co-ordinates'].str.replace(')','')
    df[['Latitude', 'Longitude']] = df.loc[:,'Co-ordinates'].str.split(',', n=1, expand=True)
    df = df.drop(['Co-ordinates'], axis=1)
    df = df.reset_index(drop=True)
    return df

In [10]:
public_art = extract2(data, 'Art')
public_art.to_csv('public_art.csv')

### Art galleries

In [30]:
data = pd.read_csv('./Data/Landamark.csv')

In [32]:
data.head(10)

,Theme,Sub Theme,Feature Name,Co-ordinates
0,Transport,Railway Station,Flemington Bridge Railway Station,"(-37.7881645889621, 144.939277838304)"
1,Mixed Use,Retail/Office/Carpark,Council House 2 (CH2),"(-37.8142591432011, 144.966638432727)"
2,Place Of Assembly,Library,The Melbourne Athenaeum Library,"(-37.8148855756416, 144.967291289941)"
3,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Carlton Gardens South,"(-37.8060684577258, 144.971266479841)"
4,Place of Worship,Church,St Francis Church,"(-37.8118847831837, 144.962422614541)"
5,Place of Worship,Church,Wesley Church,"(-37.8101576446961, 144.968168215633)"
6,Place of Worship,Church,St Augustines Church,"(-37.8169741358546, 144.954862000132)"
7,Place of Worship,Church,St James Church,"(-37.8101281201969, 144.952468571683)"
8,Place of Worship,Church,St Mary's Anglican Church,"(-37.8031663672997, 144.953761537074)"
9,Place of Worship,Church,Romanian Orthodox,"(-37.8052307297468, 144.966986444597)"

In [33]:
def extract3(data, code):
    df = data[data['Sub Theme']==code]
    df.loc[:,'Co-ordinates'] = df.loc[:,'Co-ordinates'].str.replace('(','')
    df.loc[:,'Co-ordinates'] = df.loc[:,'Co-ordinates'].str.replace(')','')
    df[['Latitude', 'Longitude']] = df.loc[:,'Co-ordinates'].str.split(',', n=1, expand=True)
    df = df.drop(['Co-ordinates'], axis=1)
    df = df.reset_index(drop=True)
    return df

In [34]:
art_gallery = extract3(data, 'Art Gallery/Museum')
art_gallery.to_csv('art_gallery.csv')

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:635: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item_labels[indexer[info_axis]]] = value
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

## Extract Business

In [13]:
bn = pd.read_csv('Data/Business_establishments__with_trading_name_and_industry_classification (1).csv')
emp = pd.read_csv('Data/Employment_per_industry_for_blocks_2017.csv')

In [24]:
bn[bn['Block ID'] == 31]

,Census year,Block ID,Property ID,Base property ID,CLUE small area,Trading name,Industry (ANZSIC4) code,Industry (ANZSIC4) description,x coordinate,y coordinate,Location
0,2004,31,102114,102114,Melbourne (CBD),Melbourne Fitness Centre,9111,Health and Fitness Centres and Gymnasia Operation,144.956218,-37.818138,"(-37.81813804, 144.9562175)"
1,2004,31,105297,105297,Melbourne (CBD),Commonwealth Bank,6221,Banking,144.955924,-37.817735,"(-37.81773521, 144.9559235)"
2,2004,31,105297,105297,Melbourne (CBD),Aioi Insurance,6419,Other Auxiliary Finance and Investment Services,144.955924,-37.817735,"(-37.81773521, 144.9559235)"
3,2004,31,105297,105297,Melbourne (CBD),Alcoa,2132,Aluminium Smelting,144.955924,-37.817735,"(-37.81773521, 144.9559235)"
4,2004,31,105297,105297,Melbourne (CBD),Wbm Consulting Engineers,6923,Engineering Design and Engineering Consulting ...,144.955924,-37.817735,"(-37.81773521, 144.9559235)"
5,2004,31,105297,105297,Melbourne (CBD),Part of Melbourne Corporation,5219,Other Water Transport Support Services,144.955924,-37.817735,"(-37.81773521, 144.9559235)"
6,2004,31,105297,105297,Melbourne (CBD),Citic Australia,6240,Financial Asset Investing,144.955924,-37.817735,"(-37.81773521, 144.9559235)"
9,2004,31,105941,105941,Melbourne (CBD),The Fiddler Pub,4520,"Pubs, Taverns and Bars",144.955606,-37.817827,"(-37.81782672, 144.955606)"
10,2004,31,105942,105942,Melbourne (CBD),Vacant,0,Vacant Space,144.955444,-37.817871,"(-37.81787118, 144.955444)"
11,2004,31,105943,105943,Melbourne (CBD),Nurse's Board of Victoria,9551,Business and Professional Association Services,144.955284,-37.817919,"(-37.81791923, 144.9552838)"
12,2004,31,105944,105944,Melbourne (CBD),Lempriere (Australia) Pty Ltd,3311,Wool Wholesaling,144.955122,-37.817965,"(-37.81796539, 144.9551217)"
14,2004,31,108968,108968,Melbourne (CBD),Kings Parking,9533,Parking Services,144.954366,-37.818185,"(-37.81818484, 144.9543659)"
15,2004,31,108968,108968,Melbourne (CBD),Department of Human Services,7520,State Government Administration,144.954366,-37.818185,"(-37.81818484, 144.9543659)"
940,2006,31,102110,102110,Melbourne (CBD),Sparkling Cafe,4511,Cafes and Restaurants,144.954944,-37.818504,"(-37.81850425, 144.954944)"
941,2006,31,102110,102110,Melbourne (CBD),Shoe Fix on Collins,9491,Clothing and Footwear Repair,144.954944,-37.818504,"(-37.81850425, 144.954944)"
2169,2006,31,102110,102110,Melbourne (CBD),City West Newsagency,4244,Newspaper and Book Retailing,144.954944,-37.818504,"(-37.81850425, 144.954944)"
2506,2006,31,102114,102114,Melbourne (CBD),Primus Telecommunications,5802,Other Telecommunications Network Operation,144.956218,-37.818138,"(-37.81813804, 144.9562175)"
2536,2006,31,105297,105297,Melbourne (CBD),Transcom Credit Co-operative,6223,Credit Union Operation,144.955924,-37.817735,"(-37.81773521, 144.9559235)"
2863,2011,31,108968,108968,Melbourne (CBD),Tahitian Tanning & Beauty,9511,Hairdressing and Beauty Services,144.954366,-37.818185,"(-37.81818484, 144.9543659)"
2864,2011,31,105297,105297,Melbourne (CBD),Defence Force Credit Union,6223,Credit Union Operation,144.955924,-37.817735,"(-37.81773521, 144.9559235)"
3393,2006,31,102110,102110,Melbourne (CBD),Ruggles Drycleaning,9531,Laundry and Dry-Cleaning Services,144.954944,-37.818504,"(-37.81850425, 144.954944)"
3394,2006,31,102110,102110,Melbourne (CBD),Eyes on West End,8532,Optometry and Optical Dispensing,144.954944,-37.818504,"(-37.81850425, 144.954944)"
3395,2006,31,102110,102110,Melbourne (CBD),Global Telesales Pty Ltd,7294,Call Centre Operation,144.954944,-37.818504,"(-37.81850425, 144.954944)"
3396,2006,31,102110,102110,Melbourne (CBD),Kids On Collins,8710,Child Care Services,144.954944,-37.818504,"(-37.81850425, 144.954944)"
3397,2006,31,102111,102111,Melbourne (CBD),Warwick's Fine Foods,4511,Cafes and Restaurants,144.954569,-37.818612,"(-37.81861166, 144.9545688)"
3398,2006,31,102111,102111,Melbourne (CBD),Spencer Square Hairdressing,9511,Hairdressing and Beauty Services,144.954569,-37.818612,"(-37.81861166, 144.9545688)"
3399,2006,31,102111,102111,Melbourne (CBD),Wonderful Garden,4512,Takeaway Food Services,144.954569,-37.818612,"(-37.81861166, 144.9545688)"
3400,2006,31,102111,102111,Melbourne (CBD),Bean Bar,4512,Takeaway Food Services,144.954569,-37.818612,"(-37.81861166, 144.9545688)"
3401,2006,31,102114,102114,Melbourne (CBD),Office Works,4272,Stationery Goods Retailing,144.956218,-37.818138,"(-37.81813804, 144.9562175)"
3402,2006,31,105297,105297,Melbourne (CBD),Commonwealth Bank,6221,Banking,144.955924,-37.817735,"(-37.81773521, 144.9559235)"
...,...,...,...,...,...,...,...,...,...,...,...
258755,2017,31,102112,102112,Melbourne (CBD),Vacant,0,Vacant Space,144.955424,-37.818366,"(-37.81836574, 144.9554244)"
258756,2017,31,102112,102112,Melbourne (CBD),Vacant,0,Vacant Space,144.955424,-37.818366,"(-37.81836574, 144.9554244)"
258757,2017,31,102109,102109,Melbourne (CBD),Bingo Wrap,4511,Cafes and Restaurants,144.954350,-37.818675,"(-37.81867544, 144.9543505)"
258758,2017,31,105297,105297,Melbourne (CBD),Mais Australia Education,8220,Educational Support Services,144.955924,-37.817735,"(-37.81773521, 144.9559235)"
258848,2017,31,105297,105297,Melbourne (CBD),Australian Dental Council Limited,9551,Business and Professional Association Services,144.955924,-37.817735,"(-37.81773521, 144.9559235)"
258854,2017,31,108968,108968,Melbourne (CBD),Adminstration Appeals Tribunal,7510,Central Government Administration,144.954366,-37.818185,"(-37.81818484, 144.9543659)"
258858,2017,31,102110,102110,Melbourne (CBD),Evocca College,8101,Technical and Vocational Education and Training,144.954944,-37.818504,"(-37.81850425, 144.954944)"
258907,2017,31,105297,105297,Melbourne (CBD),Spring Financial Group,6240,Financial Asset Investing,144.955924,-37.817735,"(-37.81773521, 144.9559235)"
259019,2017,31,108968,108968,Melbourne (CBD),Daisy Deluxe Nails and Beauty,9511,Hairdressing and Beauty Services,144.954366,-37.818185,"(-37.81818484, 144.9543659)"
259020,2017,31,105297,105297,Melbourne (CBD),Mayne Pharma Group Limited,3720,Pharmaceutical and Toiletry Goods Wholesaling,144.955924,-37.817735,"(-37.81773521, 144.9559235)"
259021,2017,31,102113,102113,Melbourne (CBD),Vacant,0,Vacant Space,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259022,2017,31,102113,102113,Melbourne (CBD),Spicy Route,4512,Takeaway Food Services,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259023,2017,31,102113,102113,Melbourne (CBD),Chatterbox Rice,4512,Takeaway Food Services,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259024,2017,31,102113,102113,Melbourne (CBD),Vacant,0,Vacant Space,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259025,2017,31,102113,102113,Melbourne (CBD),Blended Spices,4512,Takeaway Food Services,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259026,2017,31,102113,102113,Melbourne (CBD),Vacant,0,Vacant Space,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259027,2017,31,102113,102113,Melbourne (CBD),Charles Rose Collins Street,4253,Watch and Jewellery Retailing,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259028,2017,31,102113,102113,Melbourne (CBD),Rockit Barber Shop,9511,Hairdressing and Beauty Services,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259029,2017,31,102110,102110,Melbourne (CBD),Collins Barber,9511,Hairdressing and Beauty Services,144.954944,-37.818504,"(-37.81850425, 144.954944)"
259030,2017,31,102110,102110,Melbourne (CBD),7-Eleven,4111,Convenience Store,144.954944,-37.818504,"(-37.81850425, 144.954944)"
259415,2017,31,102113,102113,Melbourne (CBD),Vacant,0,Vacant Space,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259416,2017,31,102113,102113,Melbourne (CBD),Cafe Le Martin,4512,Takeaway Food Services,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259417,2017,31,102113,102113,Melbourne (CBD),Subway,4512,Takeaway Food Services,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259418,2017,31,102113,102113,Melbourne (CBD),Vacant,0,Vacant Space,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259419,2017,31,102113,102113,Melbourne (CBD),Fitness First,9111,Health and Fitness Centres and Gymnasia Operation,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259541,2017,31,102114,102114,Melbourne (CBD),City CYC,4400,Accommodation,144.956218,-37.818138,"(-37.81813804, 144.9562175)"
259542,2017,31,102113,102113,Melbourne (CBD),Vacant,0,Vacant Space,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259600,2017,31,108968,108968,Melbourne (CBD),ILSC,8101,Technical and Vocational Education and Training,144.954366,-37.818185,"(-37.81818484, 144.9543659)"
259603,2017,31,102113,102113,Melbourne (CBD),Benergy,2640,On Selling Electricity and Electricity Market ...,144.955845,-37.818245,"(-37.81824465, 144.9558446)"
259708,2017,31,108968,108968,Melbourne (CBD),Vacant,0,Vacant Space,144.954366,-37.818185,"(-37.81818484, 144.9543659)"

In [23]:
emp[emp['Block ID'] == 31]

,Census year,Block ID,CLUE small area,Accommodation,Admin and Support Services,Agriculture and Mining,Arts and Recreation Services,Business Services,Construction,Education and Training,...,Information Media and Telecommunications,Manufacturing,Other Services,Public Administration and Safety,Real Estate Services,Rental and Hiring Services,Retail Trade,"Transport, Postal and Storage",Wholesale Trade,Total employment in block
569,2017,31,Melbourne (CBD),NaN,120.0,0.0,NaN,249.0,NaN,338.0,...,NaN,NaN,50.0,NaN,0.0,0.0,99.0,NaN,NaN,2058.0

In [15]:
en_emp = pd.merge(bn, emp, on='Block ID')

In [19]:
em_emp = en_emp[['Block ID', 'Industry (ANZSIC4) description', 'x coordinate', 'y coordinate', 'Total employment in block']]

In [25]:
em_emp.to_csv('em_emp.csv')

In [26]:
em_emp.head()

,Block ID,Industry (ANZSIC4) description,x coordinate,y coordinate,Total employment in block
0,31,Health and Fitness Centres and Gymnasia Operation,144.956218,-37.818138,2058.0
1,31,Banking,144.955924,-37.817735,2058.0
2,31,Other Auxiliary Finance and Investment Services,144.955924,-37.817735,2058.0
3,31,Aluminium Smelting,144.955924,-37.817735,2058.0
4,31,Engineering Design and Engineering Consulting ...,144.955924,-37.817735,2058.0